import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg=window.CLINK_CONFIG||{};
const ok=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes("PASTE_")&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes("PASTE_");
const supabase=ok?createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let me=null, profile=null, peer=null, channel=null, placeFilter="";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(t){$("#toast").innerHTML='<div style="position:fixed;top:18px;left:50%;transform:translateX(-50%);background:#d9ff45;color:#111;padding:11px 15px;border-radius:14px;font-weight:900;z-index:99">'+esc(t)+'</div>';setTimeout(()=>$("#toast").innerHTML="",2200)}
function age(b){const d=new Date(b),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;return a}
function showAuth(){$("#auth").classList.remove("hidden");$("#main").classList.add("hidden");$("#nav").classList.add("hidden");$("#logout").classList.add("hidden")}
function showApp(){$("#auth").classList.add("hidden");$("#main").classList.remove("hidden");$("#nav").classList.remove("hidden");$("#logout").classList.remove("hidden")}
$$("[data-auth]").forEach(b=>b.onclick=()=>{const login=b.dataset.auth==="login";$("#loginForm").classList.toggle("hidden",!login);$("#signupForm").classList.toggle("hidden",login);$$("[data-auth]").forEach(x=>x.classList.toggle("primary",x===b))});
$("#loginForm").onsubmit=async e=>{e.preventDefault();if(!ok)return toast("config.js дээр Supabase холбоно уу");const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(error)toast(error.message)};
$("#signupForm").onsubmit=async e=>{e.preventDefault();if(!ok)return toast("config.js дээр Supabase холбоно уу");const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signUp({email:f.get("email"),password:f.get("password")});toast(error?error.message:"Бүртгэл үүслээ. Имэйлээ шалгана уу.")};
$("#logout").onclick=()=>supabase?.auth.signOut();
$$("[data-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function switchView(v){$$(".page").forEach(p=>p.classList.toggle("on",p.id===v));$$("[data-view]").forEach(b=>b.classList.toggle("on",b.dataset.view===v));if(v==="discover")loadDiscover();if(v==="friends")loadFriends();if(v==="chat")loadFriends();if(v==="profile")loadProfile();if(v==="tonight")loadStatus()}
async function boot(){if(!ok){$("#backendNote").textContent="Backend холбоогүй. config.js-д Supabase URL + anon key оруулна уу.";return}const {data:{session}}=await supabase.auth.getSession();if(session)await signedIn(session.user);supabase.auth.onAuthStateChange(async(_,s)=>s?await signedIn(s.user):showAuth())}
async function signedIn(u){me=u;showApp();await loadProfile();switchView(profile?"discover":"profile")}
async function loadProfile(){if(!me)return;const {data}=await supabase.from("profiles").select("*").eq("id",me.id).maybeSingle();profile=data;if(data){$("#name").value=data.display_name||"";$("#birth").value=data.birth_date||"";$("#profileProvince").value=data.province||"Улаанбаатар";$("#profileDistrict").value=data.district||"";$("#bio").value=data.bio||"";$("#avatarPreview").src=data.avatar_url||""}}
$("#profileForm").onsubmit=async e=>{e.preventDefault();if(age($("#birth").value)<21)return toast("CLINK 21+ хэрэглэгчдэд зориулагдсан");const payload={id:me.id,display_name:$("#name").value.trim(),birth_date:$("#birth").value,province:$("#profileProvince").value.trim(),district:$("#profileDistrict").value.trim(),bio:$("#bio").value.trim(),updated_at:new Date().toISOString()};const {error}=await supabase.from("profiles").upsert(payload);if(error)return toast(error.message);toast("Профайл хадгалагдлаа");await loadProfile()};
$("#photo").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024)return toast("5MB-аас бага зураг оруулна уу");const ext=(f.name.split(".").pop()||"jpg").toLowerCase(),path=`${me.id}/avatar-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("avatars").upload(path,f,{upsert:true,contentType:f.type});if(error)return toast(error.message);const {data:{publicUrl}}=supabase.storage.from("avatars").getPublicUrl(path);await supabase.from("profiles").upsert({id:me.id,avatar_url:publicUrl,updated_at:new Date().toISOString()});toast("Зураг шинэчлэгдлээ");loadProfile()};
$$("[data-place]").forEach(b=>b.onclick=()=>{$$("[data-place]").forEach(x=>x.classList.toggle("on",x===b));placeFilter=b.dataset.place;loadDiscover()});
async function loadDiscover(){if(!profile)return;let q=supabase.from("discover_profiles").select("*").neq("id",me.id).eq("province",profile.province).limit(50);if(placeFilter)q=q.eq("place",placeFilter);const {data,error}=await q;if(error)return toast(error.message);$("#people").innerHTML=(data||[]).map(p=>`<article class="card"><img src="${esc(p.avatar_url||"")}" alt=""><div class="body"><b>${esc(p.display_name)}, ${p.age||""}</b><p class="muted">${esc(p.district||"")} · ${p.place==="home"?"Гэртээ":p.place==="out"?"Гадуур":""}</p><p>${esc(p.status_bio||p.bio||"")}</p><button class="btn primary" onclick="friend('${p.id}')">＋ Friend</button></div></article>`).join("")||'<div class="panel muted">Одоогоор хүн алга.</div>'}
window.friend=async id=>{const {error}=await supabase.from("friend_requests").insert({sender_id:me.id,receiver_id:id});toast(error?(error.code==="23505"?"Request явсан байна":error.message):"Friend request илгээлээ")};
async function loadFriends(){const [{data:r},{data:f}]=await Promise.all([supabase.from("incoming_friend_requests").select("*"),supabase.from("my_friends").select("*")]);$("#requests").innerHTML=(r||[]).map(x=>`<div class="row"><img class="ava" src="${esc(x.avatar_url||"")}"><div class="grow"><b>${esc(x.display_name)}</b></div><button class="btn primary" onclick="acceptReq('${x.request_id}')">Accept</button></div>`).join("")||'<span class="muted">Request алга</span>';$("#friendList").innerHTML=(f||[]).map(x=>`<div class="row"><img class="ava" src="${esc(x.avatar_url||"")}"><div class="grow"><b>${esc(x.display_name)}</b></div><button class="btn" onclick="openChat('${x.friend_id}','${esc(x.display_name)}')">💬</button></div>`).join("")||'<span class="muted">Найз алга</span>';$("#conversations").innerHTML=(f||[]).map(x=>`<div class="row" onclick="openChat('${x.friend_id}','${esc(x.display_name)}')" style="cursor:pointer"><img class="ava" src="${esc(x.avatar_url||"")}"><b>${esc(x.display_name)}</b></div>`).join("")}
window.acceptReq=async id=>{const {error}=await supabase.rpc("accept_friend_request",{p_request_id:id});if(error)return toast(error.message);toast("Найз боллоо");loadFriends()};
window.openChat=async(id,name)=>{peer={id,name};switchView("chat");$("#chatTitle").textContent=name;$("#messageInput").disabled=false;$("#sendBtn").disabled=false;await loadMessages();if(channel)supabase.removeChannel(channel);channel=supabase.channel("dm-"+me.id+"-"+id).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},()=>loadMessages()).subscribe()};
async function loadMessages(){if(!peer)return;const {data,error}=await supabase.from("messages").select("*").or(`and(sender_id.eq.${me.id},receiver_id.eq.${peer.id}),and(sender_id.eq.${peer.id},receiver_id.eq.${me.id})`).order("created_at",{ascending:true});if(error)return toast(error.message);$("#messages").innerHTML=(data||[]).map(m=>`<div class="bubble ${m.sender_id===me.id?"me":""}">${esc(m.body)}</div>`).join("");$("#messages").scrollTop=$("#messages").scrollHeight}
$("#messageForm").onsubmit=async e=>{e.preventDefault();if(!peer)return;const body=$("#messageInput").value.trim();if(!body)return;const {error}=await supabase.from("messages").insert({sender_id:me.id,receiver_id:peer.id,body});if(error)return toast(error.message);$("#messageInput").value=""};
$("#statusForm").onsubmit=async e=>{e.preventDefault();const payload={user_id:me.id,province:$("#province").value.trim(),district:$("#district").value.trim(),place:$("#place").value,venue:$("#place").value==="home"?null:$("#venue").value.trim(),group_count:+$("#groupCount").value,status_bio:$("#statusBio").value.trim(),expires_at:new Date(Date.now()+6*3600e3).toISOString()};const {error}=await supabase.from("night_statuses").upsert(payload,{onConflict:"user_id"});toast(error?error.message:"Статус нийтлэгдлээ")};
$("#stopStatus").onclick=async()=>{const {error}=await supabase.from("night_statuses").delete().eq("user_id",me.id);toast(error?error.message:"Статус унтарлаа")};
async function loadStatus(){if(!profile)return;$("#province").value=profile.province||"Улаанбаатар";$("#district").value=profile.district||"";const {data}=await supabase.from("night_statuses").select("*").eq("user_id",me.id).maybeSingle();if(data){$("#province").value=data.province;$("#district").value=data.district;$("#place").value=data.place;$("#venue").value=data.venue||"";$("#groupCount").value=data.group_count||2;$("#statusBio").value=data.status_bio||""}}
boot();