window.CLINK_CONFIG = {
  SUPABASE_URL: "https://mtiwmycejcsxrrzpatrg.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10aXdteWNlamNzeHJyenBhdHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0NDkyNjgsImV4cCI6MjEwNzAyNTI2OH0.fohyqZrZoVX700EVRe-QWWD5RYqBIAa9Etxwhn6av6I"
};
